name: Jupyter Server Release Script
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version'
        required: true
      post_version:
        description: 'Post Version'
jobs:
  release:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu]
        python-version: ['3.9']
    env:
       VERSION: ${{ github.event.inputs.version }}
       POST_VERSION: ${{ github.event.inputs.post_version }}
       CHANGELOG: "CHANGELOG.md"
       CHANGELOG_OUTPUT: "changelog_entry.md"
       RUNNER: "python -m scripts"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Upgrade packaging dependencies
      run: |
        pip install --upgrade pip setuptools wheel --user
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        pip install -e .[publishing,test]
      - name: Get Branch from environment
      run: |
          CMD="${RUNNER}.parse_git_ref ${GITHUB_REF}"
          echo "BRANCH=$(${CMD})" >> $GITHUB_ENV
        cat ${GITHUB_ENV}
    - name: Prep Git
      run: |
        ${RUNNER}.prep_git ${GITHUB_REPOSITORY} ${BRANCH}
    - name: Run the release prep
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ${RUNNER}.bump_version ${VERSION}
        ${RUNNER}.finalize_changelog \
          ${GITHUB_REPOSITORY} ${CHANGELOG} \
          --branch upstream/${BRANCH} \
          --output ${CHANGELOG_OUTPUT}
        ${RUNNER}.prep_python_release
        ${RUNNER}.finalize_release_prep \
          --branch upstream/${BRANCH} \
          --post-version ${POST_VERSION}
        cat ${CHANGELOG_OUTPUT}
    - name: Publish PyPI Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        REGISTRY: https://test.pypi.org/legacy/
      run: |
        twine upload --repository-url ${REGISTRY} --skip-existing dist/*
    - name: Extract Final Version
      run: |
        CMD="${RUNNER}.get_final_version ${VERSION}"
        echo "FINAL_VERSION=$(${CMD})" >> $GITHUB_ENV
        cat ${GITHUB_ENV}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body_path: ${{ env.CHANGELOG_OUTPUT }}
        prerelease: ${{ env.VERSION != env.FINAL_VERSION }}
