name: Jupyter Server Release Check
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu]
        python-version: ['3.9']
    env:
       BRANCH: "master"
       VERSION: "100.5.1"
       POST_VERSION: "100.6.0.dev0"
       # TODO: REMOVE THIS IN FAVOR OF GITHUB_REPOSITORY env
       TARGET: "jupyter-server/jupyter_server"
       CHANGELOG: "CHANGELOG.md"
       CHANGELOG_OUTPUT: "changelog_entry.md"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Upgrade packaging dependencies
      run: |
        pip install --upgrade pip setuptools wheel --user
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    - name: Prep Git
      env:
        BRANCH: "master"
      run: |
        python scripts/git_prep_script.py \
          jupyter-server/jupyter_server ${BRANCH}
    - name: Install Dependencies
      run: pip install -e .[publishing]
    - name: Run the changelog prep      
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/changelog_prep_script.py \
          ${TARGET} ${CHANGELOG} \
          --version ${VERSION} \
          --output ${CHANGELOG_OUTPUT} \
          --branch upstream/${BRANCH}
        cat ${CHANGELOG_OUTPUT}
        # Store the new version
        echo "NEW_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
    - name: Make a PR with the changelog entry change
      run: |
        echo "Can't make a PR on the release check"
        # uses: peter-evans/create-pull-request@v3
        # title="Automated Changelog for ${NEW_VERSION} on ${BRANCH}"
        # branch-suffix=timestamp
        # delete-branch=true
        # base=${BRANCH}
        # body="Automated Changelog for ${NEW_VERSION} on ${BRANCH} using version specifier ${VERSION}"
    - name: Run the release prep      
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/release_prep_script.py \
          ${TARGET} ${CHANGELOG} \
          --version ${VERSION} \
          --post-version ${POST_VERSION} \
          --output ${CHANGELOG_OUTPUT} \
          --branch upstream/${BRANCH}
        cat ${CHANGELOG_OUTPUT}
    - name: Publish PyPI Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        REGISTRY: https://test.pypi.org/legacy/
      run: |
        twine upload --repository-url ${REGISTRY} --skip-existing dist/*
    - name: Extract Final Version
      run: |
        echo "FINAL_VERSION=$(echo ${VERSION} | egrep "[0-9]+\.[0-9]+\.[0-9]+")" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body_path: ${{ env.CHANGELOG_OUTPUT }}
        prerelease: ${{ env.VERSION != env.FINAL_VERSION }}
        draft: true
    - name: Delete Draft Release
      env:
        RELEASE_ID: ${{ steps.create_release.outputs.id }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HTML_URL: ${{ steps.create_release.outputs.html_url}}
      run: |
        echo "For release check we don't want to leave a draft release open"
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}
    - name: Push the commit(s) and tag(s) to the branch
      run: |
        echo "Can't push on the release check"
        # needs GITHUB_TOKEN in final version
        # git push upstream ${BRANCH} --tags